//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WNG.NCS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SequenceNumber
    {
        public int SequenceNumberId { get; set; }
        public int Number { get; set; }
        public bool IsOdd { get; set; }
        public bool IsEven { get; set; }
        public bool IsMultipleBy3 { get; set; }
        public bool IsMultipleBy5 { get; set; }
        public bool IsFibonacci { get; set; }
    }
}
